language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

services:
  - mysql

before_script:
  - phpenv config-rm xdebug.ini
  - mysql -e 'CREATE DATABASE shinage_test;'
  - cp .env.travis .env
  - composer install --no-scripts
  - npm install
  - NODE_ENV=production ./node_modules/.bin/gulp
  - php bin/console assets:install --env=test
  - php bin/console doctrine:migrations:migrate -n --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
  - php bin/console server:start 127.0.0.1:8000 --env=test

script:
  - ./vendor/bin/ecs check src/ features/bootstrap/
  - ./node_modules/.bin/gulp eslint
  - ./bin/console lint:yaml config/
  - ./bin/console lint:yaml src/
  - ./bin/console lint:yaml translations/
  - ./bin/console lint:twig config/
  - ./bin/console lint:twig src/
  - ./bin/console lint:twig templates/
  - ./vendor/bin/phpspec run --format=progress --no-code-generation
  - ./vendor/bin/behat --format=progress --strict -n --tags="~@todo"

after_failure:
  - echo "Printing some debug information:"
  - php -i
  - cat ./var/log/test.log

before_deploy:
  - mkdir ./build
  - rm -f .scrutinizer.yml .travis.yml .gitignore .web-server-pid
  - rm -f easy-coding-standard.yml package* behat.yml codeception.yml install-git-hooks.php phpspec.yml gulpfile.js
  - rm -rf node_modules/  var/cache/dev/ var/cache/test/ var/session/dev/ var/session/test/ .git/ etc/ features/ git-hooks/ vendor
  - echo "${TRAVIS_BRANCH}" > REVISION
  - composer install --no-scripts --no-dev
  - tar --exclude="./build" --exclude="./var/logs/*.log" --transform 's,^\./,,' -czf ./build/shinage-server-release.tar.gz .

deploy:
  provider: releases
  api_key:
    secure: "RWMR90jWRYx2Bezal5+T/pQaXUQhHG7+pHSwV+uKjlLOEVtmWKQRCdmPl0LHc2TcOpDor/ql9fjE9PocoKp+xsZSBWhA8mgfp6RLC5yM9bUBQgvawibuRdyxfxA8D0K8aju3bt5+qvuER8OQrvle4knHwPu2LQC5Q0ZKz5wxH4xAdcuBoWKG2iEhupCKienvnapXKBvFFrvrbjff4Fi+/HQsbon+RndlQgoj1pQ5Q1mxq4EiQQYvRBseyf0BFfPUt51AUtCQIzwrf4w+2rlE+45RDrkCqa6M5exRpSu2haB+h7/nRNErstyUP+V+0Jw6ftSOBxt1xcBiHkklBKpaIfzFsNax+erxv35oOFs2xhTigZNhwJCLsvv/UL6mqCnAUmmVrj6mD4rOXKdVVdI4WBOq5F4y6bpqfOLvboVbXpWoyCRD/zwnd6EQdIEX/2/dtIRFZJIv2lxl8C6baifpIZCkwyVoaN5cxQrxs1sTe4/z3Bkt+cG5TaYI+nr9Aeve5NtAxo5SrRHA/UtBeAJxdHSjYbwXvYp6rTodUz9sAO7KinDbiMAiTPzZEOmxbKD0fBSXxv1ZeC7R5Qsb4fTlHTlRaK3Xu5zSePJRYtBfXXGS/1IzHhhAZzoDklBXzSBQ1HllAkY9IBCZ42nBVklP1zEYBMoyuaBHGSai4Hpc9kM="
  file: "./build/shinage-server-release.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    php: 7.1
