# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.screenassociation:
        class: AppBundle\Service\ScreenAssociation
        arguments:
            em: "@doctrine.orm.entity_manager"
            tokenStorage: "@security.token_storage"

    app.filepool:
        class: AppBundle\Service\FilePool
        arguments:
            basepath: "%path_pool%"

    app.apiroleregistry:
        class: AppBundle\Service\ApiRoleRegistry

    app.todolist:
        class: AppBundle\Service\TodoList
        arguments:
            basepath: "%kernel.root_dir%"
            cache: "@cache.app"

    app.registration.listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments:
            router: "@router.default"
        tags:
            - { name: kernel.event_subscriber }

    app.form.type.owner:
        class: AppBundle\Form\Type\OwnerType
        arguments:
            em: "@doctrine.orm.entity_manager"
            tokenStorage: "@security.token_storage"
        tags:
            - { name: form.type }

    app.form.type.apikeyform:
        class: AppBundle\Form\ApiKeyForm
        arguments:
            em: "@doctrine.orm.entity_manager"
            tokenStorage: "@security.token_storage"
        tags:
            - { name: form.type }