version: '3'

services:
  nginx:
    image: nginx:1.14-alpine
    environment:
      - VIRTUAL_HOST=shinage.localhost
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ${PROJECT_DIR}:/usr/share/nginx/html:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./nginx/server.crt:/opt/server.crt:delegated
      - ./nginx/server.key:/opt/server.key:delegated
    links:
      - php
      - mariadb
    depends_on:
      - php

  php:
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ${PROJECT_DIR}:/usr/share/nginx/html:delegated
      - ${PROJECT_DIR}/.env.dev-docker:/usr/share/nginx/html/.env:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini:delegated
    links:
      - mariadb
      - mailhog
      - redis
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_DATABASE=${PROJECT_NAME}
    ports:
      - "${MARIADB_PORT}:3306"

  redis:
    image: redis:5-alpine
    ports:
      - "${REDIS_PORT}:6379"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${MAILHOG_PORT}:8025"

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    links:
      - mariadb
    depends_on:
      - mariadb
